package org.nilohit.movies;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2017-11-06T21:56:31.536-06:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "MovieService", 
                  wsdlLocation = "file:/C:/Users/jhani/udemy_workspace/multiModuleProjectSpace/bookMyFlick/services/src/main/webapp/WEB-INF/movies.wsdl",
                  targetNamespace = "http://www.nilohit.org/movies/") 
public class MovieService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.nilohit.org/movies/", "MovieService");
    public final static QName MovieOrdersPort = new QName("http://www.nilohit.org/movies/", "movieOrdersPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/jhani/udemy_workspace/multiModuleProjectSpace/bookMyFlick/services/src/main/webapp/WEB-INF/movies.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MovieService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/jhani/udemy_workspace/multiModuleProjectSpace/bookMyFlick/services/src/main/webapp/WEB-INF/movies.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MovieService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MovieService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MovieService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MovieService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MovieService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MovieService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns CustomerMovieOrdersPortType
     */
    @WebEndpoint(name = "movieOrdersPort")
    public CustomerMovieOrdersPortType getMovieOrdersPort() {
        return super.getPort(MovieOrdersPort, CustomerMovieOrdersPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerMovieOrdersPortType
     */
    @WebEndpoint(name = "movieOrdersPort")
    public CustomerMovieOrdersPortType getMovieOrdersPort(WebServiceFeature... features) {
        return super.getPort(MovieOrdersPort, CustomerMovieOrdersPortType.class, features);
    }

}
