package org.nilohit.movies;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2017-11-12T11:44:47.828-06:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://www.nilohit.org/movies/", name = "CustomerMovieOrdersPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerMovieOrdersPortType {

    @WebResult(name = "cancelMyMovieResponse", targetNamespace = "http://www.nilohit.org/movies/", partName = "parameters")
    @WebMethod(operationName = "CancelMyMovies", action = "http://www.nilohit.org/movies/NewOperation")
    public CancelMyMovieResponse cancelMyMovies(
        @WebParam(partName = "parameters", name = "cancelMyMovieRequest", targetNamespace = "http://www.nilohit.org/movies/")
        CancelMyMovieRequest parameters
    );

    @WebResult(name = "showAllMovieResponse", targetNamespace = "http://www.nilohit.org/movies/", partName = "parameters")
    @WebMethod(operationName = "GetMovies", action = "http://www.nilohit.org/movies/NewOperation")
    public ShowAllMovieResponse getMovies(
        @WebParam(partName = "parameters", name = "showAllMovieRequest", targetNamespace = "http://www.nilohit.org/movies/")
        ShowAllMovieRequest parameters
    );

    @WebResult(name = "bookMyMovieResponse", targetNamespace = "http://www.nilohit.org/movies/", partName = "parameters")
    @WebMethod(operationName = "BookMyMovies", action = "http://www.nilohit.org/movies/NewOperation")
    public BookMyMovieResponse bookMyMovies(
        @WebParam(partName = "parameters", name = "bookMyMovieRequest", targetNamespace = "http://www.nilohit.org/movies/")
        BookMyMovieRequest parameters
    );
}
